version: '3'
output: interleaved

var:
  UI: ./ts
  PY: ./py

tasks:
  ts:
    cmds:
      - cd ts && bun run dev
    prefix: ui

  py:
    cmds:
      - cd py && uv run main.py

  dev:
    deps:
      - ts
      - py